title: Thomas Hoefler | Virologist
description: Evolutionary and molecular genetics of viral infections
author: Thomas Hoefler
avatar: /lablogo.png
email: hoeft@ksu.edu

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
#  - jekyll-feed

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

 Jekyll SEO Tag (Optional)
 =========================
twitter:
  username: Hoef_Th
  card: summary
logo: head.jpg
social:
  name: Thomas Hoefler
  links:
    - https://x.com/Hoef_Th
    - https://www.linkedin.com/in/thomas-h√∂fler-0146a81a3?trk=people-guest_people_search-card
    - https://github.com/hoeflet
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
